name: Check Gym Capacity

on:
  schedule:
    # Run every 25 minutes during 14:00-17:00
    - cron: '*/10 12-15 * * *'
    # Run every 25 minutes during 21:00-00:00
    - cron: '*/10 19-22 * * *'
  workflow_dispatch:  # Allows manual triggering

# Add concurrency to prevent overlapping runs
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check-capacity:
    runs-on: ubuntu-latest
    timeout-minutes: 5  # Add timeout to prevent hung jobs
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run capacity check script
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: python src/main.py
      continue-on-error: false  # Explicitly fail the workflow if script fails
